version: "3.3"
services:
  db:
    image: postgres:12-alpine
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - djangonetwork
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    healthcheck:
      test: ["CMD-SHELL", "psql -h localhost -U $${POSTGRES_USER} -c select 1 -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build:
      dockerfile: ../docker/Dockerfile-backend
      context: ./backend/
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    volumes:
      - .:/backend-code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - djangonetwork
    links:
      - db:database
  
  # web:
  #   build:
  #     dockerfile: ../docker/Dockerfile-webapp
  #     context: ./webapp/
  #   depends_on:
  #     - backend
  
  # nginx:
  #   build:
  #     dockerfile: ../docker/Dockerfile-server
  #     context: ./nginx
  #   expose:
  #     - 80
  #   depends_on:
  #     - backend
  #     - web

networks:
  djangonetwork:
    driver: bridge

volumes:
  db:
    driver: local
