# Generated by Django 4.1.5 on 2023-01-10 19:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('story', models.TextField(blank=True, null=True)),
                ('pc', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('current_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineDot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.chronicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VampireClan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VampireDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.character')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.discipline')),
                ('dots', models.ManyToManyField(to='src.disciplinedot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VampireCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('embrace_date', models.DateTimeField(blank=True, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.character')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.vampireclan')),
                ('sire', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vampire_sire', to='src.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='V5CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.SmallIntegerField(default=1)),
                ('dexterity', models.SmallIntegerField(default=1)),
                ('stamina', models.SmallIntegerField(default=1)),
                ('charisma', models.SmallIntegerField(default=1)),
                ('manipulation', models.SmallIntegerField(default=1)),
                ('composure', models.SmallIntegerField(default=1)),
                ('intelligence', models.SmallIntegerField(default=1)),
                ('wits', models.SmallIntegerField(default=1)),
                ('resolve', models.SmallIntegerField(default=1)),
                ('athletics', models.SmallIntegerField(default=0)),
                ('brawl', models.SmallIntegerField(default=0)),
                ('craft', models.SmallIntegerField(default=0)),
                ('drive', models.SmallIntegerField(default=0)),
                ('firearms', models.SmallIntegerField(default=0)),
                ('larceny', models.SmallIntegerField(default=0)),
                ('melee', models.SmallIntegerField(default=0)),
                ('stealth', models.SmallIntegerField(default=0)),
                ('survival', models.SmallIntegerField(default=0)),
                ('animal_ken', models.SmallIntegerField(default=0)),
                ('etiquette', models.SmallIntegerField(default=0)),
                ('insight', models.SmallIntegerField(default=0)),
                ('intimidation', models.SmallIntegerField(default=0)),
                ('leadership', models.SmallIntegerField(default=0)),
                ('performance', models.SmallIntegerField(default=0)),
                ('persuasion', models.SmallIntegerField(default=0)),
                ('streetwise', models.SmallIntegerField(default=0)),
                ('subterfuge', models.SmallIntegerField(default=0)),
                ('academics', models.SmallIntegerField(default=0)),
                ('awareness', models.SmallIntegerField(default=0)),
                ('finance', models.SmallIntegerField(default=0)),
                ('investigation', models.SmallIntegerField(default=0)),
                ('medicine', models.SmallIntegerField(default=0)),
                ('occult', models.SmallIntegerField(default=0)),
                ('politics', models.SmallIntegerField(default=0)),
                ('science', models.SmallIntegerField(default=0)),
                ('technology', models.SmallIntegerField(default=0)),
                ('health', models.SmallIntegerField(default=0)),
                ('humanity', models.SmallIntegerField(default=0)),
                ('willpowet', models.SmallIntegerField(default=0)),
                ('ansia', models.SmallIntegerField(default=0)),
                ('blood_potence', models.SmallIntegerField(default=0)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.chronicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlotStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.plot')),
            ],
        ),
        migrations.CreateModel(
            name='MeritDots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.SmallIntegerField(default=1)),
                ('merit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.merit')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.chronicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HumanCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField()),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(choices=[('Love', (('lover', 'Lover'), ('married', 'Married'))), ('enemy', 'Enemy'), ('friend', 'Friend')], max_length=10)),
                ('character1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_character1', to='src.character')),
                ('character2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_character2', to='src.character')),
            ],
            options={
                'unique_together': {('character1', 'character2')},
            },
        ),
        migrations.CreateModel(
            name='CharacterMerits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.character')),
                ('merit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.meritdots')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='character',
            name='chronicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.chronicle'),
        ),
        migrations.AddField(
            model_name='character',
            name='relationships',
            field=models.ManyToManyField(through='src.CharacterRelationship', to='src.character'),
        ),
    ]
