# Generated by Django 4.1.5 on 2023-01-09 22:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('story', models.TextField(blank=True, null=True)),
                ('pc', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('current_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chronicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chronicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlotStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plot')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('chronicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chronicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(choices=[('Love', (('lover', 'Lover'), ('married', 'Married'))), ('enemy', 'Enemy'), ('friend', 'Friend')], max_length=10)),
                ('character1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_character1', to='core.character')),
                ('character2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_character2', to='core.character')),
            ],
            options={
                'unique_together': {('character1', 'character2')},
            },
        ),
        migrations.AddField(
            model_name='character',
            name='chronicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chronicle'),
        ),
        migrations.AddField(
            model_name='character',
            name='relationships',
            field=models.ManyToManyField(through='core.CharacterRelationship', to='core.character'),
        ),
    ]
