# Generated by Django 4.1.5 on 2023-01-09 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineDot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vampire.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VampireClan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VampireDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vampire.discipline')),
                ('dots', models.ManyToManyField(to='vampire.disciplinedot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VampireCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('embrace_date', models.DateTimeField(blank=True, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vampire.vampireclan')),
                ('sire', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vampire_sire', to='core.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='V5CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.SmallIntegerField(default=1)),
                ('dexterity', models.SmallIntegerField(default=1)),
                ('stamina', models.SmallIntegerField(default=1)),
                ('charisma', models.SmallIntegerField(default=1)),
                ('manipulation', models.SmallIntegerField(default=1)),
                ('composure', models.SmallIntegerField(default=1)),
                ('intelligence', models.SmallIntegerField(default=1)),
                ('wits', models.SmallIntegerField(default=1)),
                ('resolve', models.SmallIntegerField(default=1)),
                ('athletics', models.SmallIntegerField(default=0)),
                ('brawl', models.SmallIntegerField(default=0)),
                ('craft', models.SmallIntegerField(default=0)),
                ('drive', models.SmallIntegerField(default=0)),
                ('firearms', models.SmallIntegerField(default=0)),
                ('larceny', models.SmallIntegerField(default=0)),
                ('melee', models.SmallIntegerField(default=0)),
                ('stealth', models.SmallIntegerField(default=0)),
                ('survival', models.SmallIntegerField(default=0)),
                ('animal_ken', models.SmallIntegerField(default=0)),
                ('etiquette', models.SmallIntegerField(default=0)),
                ('insight', models.SmallIntegerField(default=0)),
                ('intimidation', models.SmallIntegerField(default=0)),
                ('leadership', models.SmallIntegerField(default=0)),
                ('performance', models.SmallIntegerField(default=0)),
                ('persuasion', models.SmallIntegerField(default=0)),
                ('streetwise', models.SmallIntegerField(default=0)),
                ('subterfuge', models.SmallIntegerField(default=0)),
                ('academics', models.SmallIntegerField(default=0)),
                ('awareness', models.SmallIntegerField(default=0)),
                ('finance', models.SmallIntegerField(default=0)),
                ('investigation', models.SmallIntegerField(default=0)),
                ('medicine', models.SmallIntegerField(default=0)),
                ('occult', models.SmallIntegerField(default=0)),
                ('politics', models.SmallIntegerField(default=0)),
                ('science', models.SmallIntegerField(default=0)),
                ('technology', models.SmallIntegerField(default=0)),
                ('health', models.SmallIntegerField(default=0)),
                ('humanity', models.SmallIntegerField(default=0)),
                ('willpowet', models.SmallIntegerField(default=0)),
                ('ansia', models.SmallIntegerField(default=0)),
                ('blood_potence', models.SmallIntegerField(default=0)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeritDots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.SmallIntegerField(default=1)),
                ('merit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vampire.merit')),
            ],
        ),
        migrations.CreateModel(
            name='HumanCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField()),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterMerits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.character')),
                ('merit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vampire.meritdots')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
