server {
    listen 80;
    server_name         storytdb.com www.storytdb.com;
    access_log          logs/storytdb.access.log main;

    location ~ ^/back/ {
        proxy_pass      http://127.0.0.1:8000;
    }

    location / {
        proxy_pass      http://127.0.0.1:3000;
    }
}